spring:
  application:
    name: security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: test
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      show_sql: true
jwt:
  secret: nowsoptnowsoptnownownononwonwownwownownwowno

